'use strict';
window.DIALOGUES = [
  "Server unreachable. I'm currently somewhere deep in the forest. Apparently I need internet to buy Starlink. Walking toward the city... help me to find the city!",
  "I am currently stranded in the deep forest! Starlin wants me to buy their satellite service, but without internet how am I supposed to pay for it?",
  "My home server is currently down! I'm heading towards the city on foot. Please try again in a bit!",
  "No server signal out here in the wilderness... just trees, pinecones, and questionable survival choices.",
  "Starlin sent a bill: 'Pay now for high-speed internet!' But I need internet TO pay the bill! Catch-22 in the wild!",
  "Searching for a cell tower... or a server rack... or any sign of electricity.",
  "Is it just me, or does every single tree look completely identical when you're lost?",
  "Note to self: never take a 'quick shortcut' through an unexplored thick forest.",
  "Did that bush just rustle, or is my imagination actively trying to give me a heart attack?",
  "I should have brought a map... or a compass... or honestly, just a bag of potato chips.",
  "I swear on my life I passed that exact mossy boulder twenty minutes ago.",
  "Why did I ever think a solo forest trek sounded 'peaceful and soul-cleansing'?",
  "If I survive this hike, I am legally binding myself to my couch for the rest of eternity.",
  "My feet feel like lead, but at least the scenery hasn't changed a single bit in five miles.",
  "Just me, the endless trees, and about ten thousand unseen bugs evaluating my taste.",
  "Water... I would trade my soul for a freezing cold bottle of water right now.",
  "The fresh air is great, but I really miss paved roads and streetlights.",
  "Is it getting darker, or is the canopy just getting greedier with the sunlight?",
  "I hear water dripping somewhere nearby... or it's a snake slithering through dry leaves.",
  "My phone battery is at 4%. Enough to use the flashlight for three minutes or take one last selfie.",
  "Whoever named this 'The Scenic Route' clearly had a sadistic sense of humor.",
  "My legs are operating on 99% muscle memory and 1% sheer panic.",
  "I've stepped in three different mud pits, each deeper than my life savings.",
  "I wonder if birds chirp to communicate, or if they're just gossiping about how lost I am.",
  "Nature is beautiful on a 4K desktop wallpaper. In real life, it's mostly thorny branches in the eyes.",
  "If a bear attacks me, I hope it knows I have zero nutritional value and high sodium levels.",
  "My backpack feels like it's stuffed with anvil lead and bad life choices.",
  "I used to complain about elevator wait times. Now I'm climbing a 45-degree slope on bare rocks.",
  "I thought I heard a river flowing, but it was just wind rustling through dry pine leaves.",
  "I've been walking for three hours and I'm pretty sure I'm just orbiting the same oak tree.",
  "My boots were advertised as 'all-terrain'. Apparently all-terrain means soaking up mud like a sponge.",
  "If I had a dollar for every time a twig scratched my ankle, I could buy a rescue helicopter.",
  "I'm at that stage of exhaustion where talking out loud to trees seems completely rational.",
  "The air is so clean out here it's actually making my smog-accustomed lungs suspicious.",
  "I tried to use the sun to navigate, but the sun is currently hiding behind three miles of dark clouds.",
  "I'm 90% sure a squirrel just threw a acorn at my head on purpose.",
  "Starlin promised high-speed satellite internet to this jungle, but without electricity, how am I supposed to scan the QR code to recharge my plan?",
  "Thanks to Starlin, the monkeys now have 5G Wi-Fi, but I still can't load an emergency map.",
  "Starlin installed a satellite dish on a coconut tree. The signal is great until a sloth falls on it.",
  "Starlin customer support said my signal is blocked by 'dense foliage'. Sir, I am in a forest!",
  "Great, Starlin speed is 300 Mbps in the canopy, but I'm grounded down here with zero bars and two bears.",
  "Starlin sent an automated text: 'Enjoy high-speed connectivity in nature!' Thanks Elon, I'm currently trapped in a thorny bush.",
  "Starlin dish is auto-aligning to the constellation while I'm auto-aligning my body away from a beehive.",
  "Starlin satellite overhead is transmitting 4K video streams while I'm transmitting desperate scream signals.",
  "Doodle Maps just said 'Turn right in 20 meters into a ravine'. Thanks, Goggles, very helpful in snake territory.",
  "Doodle Assistant told me to recalculate route. The route is mud, Goggles! Just thick mud!",
  "Goggles Lens identified this berry as 'possibly edible or highly lethal'. Fantastic accuracy.",
  "I searched Doodle for 'how to escape bear', and it showed me 3 sponsored ads for bear-themed t-shirts.",
  "Goggles Street View actually sent a car here in 2012. You can still see its skeleton near the river.",
  "Doodle Drive says my cloud storage is full. Can I upload this heavy backpack to the cloud instead?",
  "Goggles Assistant asked 'Did you mean: how to survive in the wilderness?' YES, Goggles, that's what I meant!",
  "Doodle Chrome has 45 tabs open in my brain right now, and all of them are panicking.",
  "Goggles Translate tried to translate bird noises and came back with 'You are trespassing on owl property'.",
  "Doodle Photos just created a memory slideshow titled 'Fun Trip to the Woods!' featuring photos of me looking terrified.",
  "Goggles Pay doesn't accept pinecones. I checked.",
  "Beta promised me the Metaverse would replace real nature. Well, at least in Beta I could mute the mosquitoes.",
  "Handbook told me 42 high school acquaintances are 'thinking of me'... yet zero sent a search party to this swamp.",
  "Neta AI algorithm recommended I join the group 'People Who Love Getting Lost in Dense Forests'. Very funny.",
  "I tried to double-tap a glowing mushroom to like it. Handbook has completely ruined my brain.",
  "Beta avatar customization costs $15 for virtual boots, while my real boots are currently filled with mud.",
  "Handbook flagged my SOS message as 'spam or misleading content'. Thanks Mark, super helpful.",
  "Handbook Status Update: 'Currently exploring the deep wilderness!' Likes: 3. Comments: 'Stay safe lol'. Send help!",
  "Neta Horizon Workrooms wanted me to attend a virtual board meeting from a tree branch.",
  "Handbook Marketplace has a listing for 'Used Compass - slightly haunted'. Honestly, I'm considering it.",
  "Neta AI generated a motivational quote for me: 'The wild is a canvas'. Great, but the canvas has wolves.",
  "Amazing promised 2-hour drone delivery to any GPS coordinate. The drone got hijacked by a family of baboons.",
  "I ordered a compass on Amazing Prime, but the package was left 'at the front door'. Which bush is the front door?!",
  "Amazing Alexa in my smartwatch just said: 'Item added to cart: Anti-venom kit. Estimated delivery: 3 business days'. I'll be a fossil by Tuesday!",
  "Amazing Fresh wants to deliver organic kale here. Nature ALREADY delivered kale everywhere, it's called WEEDS!",
  "Amazing Logistics driver marked my delivery as 'hand-delivered to resident'. Resident was a badger!",
  "Amazing Prime Video is playing a survival documentary while I'm living the actual survival nightmare.",
  "Amazing Kindle battery lasts 6 weeks, but my willpower in this forest lasted 6 minutes.",
  "Cracked-Apple charged me $999 for the iBranch stick, and it didn't even come with leaves in the box.",
  "My Pineapple Watch just warned me: 'High heart rate detected, take a breath'. BRO, THERE IS A TIGER BEHIND ME!",
  "Cracked-Apple removed the charging port from the new iForest. Now I need an iLeaf dongle.",
  "Cracked-Apple Maps directed me to a 'Genius Bar' in the middle of a mangrove swamp.",
  "Pineapple AirTag says my backpack is 'near you'. Yes, I'm wearing it, you overpriced coin!",
  "Pineapple Vision Pro would let me see a virtual beach, but I'd still be stepping on real sharp rocks.",
  "Cracked-Apple Care doesn't cover water damage from falling into a forest creek. Color me surprised.",
  "Micro-softie is forcing a Windows 11 update right now. Excellent, my digital compass needs a 4GB restart.",
  "A blue screen of death popped up on my HUD. Even in the wild, Micro-softie finds a way to crash.",
  "Micro-softie Excel would love to format this swamp location as a Date: Jan 1st, 1900.",
  "Micro-softie Teams status: 'Away'. Yes, away in an uncharted jungle with no emergency exit.",
  "Micro-softie Clippy popped up in my head saying: 'It looks like you're trying to survive. Need help?' YES CLIPPY!",
  "The Tomato delivery guy called asking for a landmark. I told him 'the big mossy rock near the angry wolf'.",
  "Goober driver cancelled my ride because 'pickup location has too many roots'.",
  "Swiggy-Piggy said 'Your food is 5 minutes away', but the delivery rider was last seen being chased by a cheetah.",
  "Goober Auto surge pricing in the forest is 8.5x. I don't even have 8.5 cents.",
  "Tomato review: 1 star. Delivery partner refused to swim across the river to hand me my biryani.",
  "Elongated Dusk wants to colonize Mars, but his Test-la battery dies the moment a pinecone hits the windshield.",
  "Test-la Cybertruck autopilot got confused by a tree stump and tried to park inside a bear cave.",
  "Elongated Dusk tweeted: 'Forests are over-rated, underground tunnels are the future'. Easy for a billionaire to say!",
  "Open-Brain AI assured me this mushroom is 99.4% edible. What about the other 0.6%? Sudden organ shutdown?",
  "I asked Chat-GPTish for a survival tip, and it generated a 5-paragraph apology for being an AI language model.",
  "Chat-GPTish prompt: 'How to make a fire with wet twigs'. Answer: 'As an AI, I recommend purchasing matches from a licensed vendor'. HELPFUL!",
  "Nut-flix just asked 'Are you still watching?' No, I am currently being watched by an owl.",
  "Dizzy acquired the copyright for this forest, so now every squirrel owes them 15% streaming royalties.",
  "Insta-Gram filters can't hide the pure terror in my eyes right now.",
  "Tik-Tokker dance trend in the forest: 'How to dodge poison ivy in 3 easy steps'.",
  "Nut-flix true crime docuseries about my hike will be titled: 'He Took The Short Cut'.",
  "Work-from-forest sounded romantic on LinkedIn until the Wi-Fi signal was eaten by a woodpecker.",
  "My manager emailed asking if I can join a quick Zoom sync. Sure, let me ask the grizzly bear to hold the camera.",
  "Corporate HR sent a wellness survey: 'How supported do you feel today?' On a scale of 1 to getting eaten by ants?",
  "LinkedIn influencers would call getting stranded in a forest a 'pivotal networking opportunity with apex predators'.",
  "If a tree falls in the forest and no one posts it on Handbook, did it even generate engagement?",
  "HR said taking a mental health walk is encouraged. They didn't mention the walk spans 40 kilometers of unexplored wilderness.",
  "My smartwatch says I've achieved my 10,000 steps goal. Great! Where's my trophy? A rescue helicopter?",
  "Synergy, bandwidth, pivot... none of these buzzwords work on a rattlesnake.",
  "I have 0% battery, 0% water, but 100% unread promotional emails from retail brands.",
  "Out of office auto-reply: 'I am currently in a forest. If urgent, please contact the nearest ranger station'.",
  "Quarterly KPI report: Walked 15 miles, fought 0 bears (yet), consumed 3 wild berries of unknown toxicity.",
  "My corporate team-building exercise was supposed to be escape room, not escape jungle!"
];
